### ISSUE TITLE
Newline after LS

### ISSUE THREAD

**Issue by alexozer** [desyncr/auto-ls#5]
Although the newline after ls is potentially helpful, it makes the behavior different from a normal `ls` so it's a it jarring. Could there be an option to disable it?

**Comment by desyncr** [comment]
Hey @alexozer! Currently there is no option available. But you can disable this way:

Define a function before loading auto-ls:

```
auto-ls-ls () {
  ls
}
```
Remember you can create your own functions or adapt the existing ones (ls and git-status).

Hope it's helpful!

**Comment by desyncr** [comment]
I'll add an option anyways as it's quite simple to do so.

**Comment by alexozer** [comment]
Ah cool, thanks!

**Comment by desyncr** [comment]
Done, now you can configure it with `AUTO_LS_NEWLINE`.
